### ISSUE TITLE
Installation does not work for Ubuntu 18.04 with v2.4

### ISSUE THREAD

**Issue by privatejava** [BrentBaccala/collaborate#31]
I tried to install everything with the wiki in Ubuntu 18.04 but I keep getting an error of gpg key of ubuntu. 

```
wget -O- -q https://raw.githubusercontent.com/BrentBaccala/bbb-install/master/bbb-install.sh | sudo bash -s -- -v bionic-240 -r www.freesoft.org -w -s vnc.mydomain.com -e my@email.com
```

```
W: GPG error: https://www.freesoft.org/bionic-240 bigbluebutton-bionic InRelease: The following signatures were invalid: EXPKEYSIG 263C57A3615C9918 Brent Baccala <cosine@freesoft.org>
W: The repository 'http://www.freesoft.org/bionic-240 bigbluebutton-bionic InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

It seems like the key is not available or expired. As per documentation of install it says it only supports for Ubuntu 18. I tried with Ubuntu 20 too but I failed with different error.

**Comment by BrentBaccala** [comment]
Thank you for the bug report!

The key had expired, and I reset its expiration date.

There was also another problem that required one of the packages to be updated.

It should work now.  I'm closing the issue, but please let me know if you still have any problems.
