### ISSUE TITLE
Issue in  bbb-auth-jwt module - Getting Signature has expired

### ISSUE THREAD

**Issue by privatejava** [BrentBaccala/collaborate#32]
Hi, 
I have been trying to install using the Installation guie in "Wiki" but when I reached at this stage for crating new login from cli I got Invalid Signature has expired issue.

the command that i put was : 
`bbb-mklogin -e "March 1 2021" -m "Brent Baccala"`

and there was a cli response with : 
```
/usr/lib/python3/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.26.14) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
https://<my-domain>/login/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJCcmVudCBCYWNjYWxhIiwicm9sZSI6Im0iLCJleHAiOjE2MTQ1NTY4MDB9.AU-0fR4obi-hlmDrSCKbneOYKnsVdS_pgsI1-uNjYU4
```

Now when I open this URL in browser I get an error of signature in Browser.

```
Something went wrong!
Signature has expired

Traceback (most recent call last):
  File "/usr/share/bbb-auth-jwt/bbb-auth-jwt", line 102, in login
    decoded = jwt.decode(jwt = JWT, key = bigbluebutton.securitySalt(), algorithms = ['HS256'])
  File "/usr/lib/python3/dist-packages/jwt/api_jwt.py", line 90, in decode
    self._validate_claims(payload, merged_options, **kwargs)
  File "/usr/lib/python3/dist-packages/jwt/api_jwt.py", line 120, in _validate_claims
    self._validate_exp(payload, now, leeway)
  File "/usr/lib/python3/dist-packages/jwt/api_jwt.py", line 161, in _validate_exp
    raise ExpiredSignatureError('Signature has expired')
jwt.exceptions.ExpiredSignatureError: Signature has expired
```

I tried installing ` bbb-auth-jwt` correctly but could not figure out why it is showing an error. Is there some BBB_SECRET needs to be updated somewhere which ` bbb-auth-jwt` and `bbb` has to be synced?

**Comment by BrentBaccala** [comment]
The `-e` option to `bbb-mklogin` sets the expiration date for the token, so copying the command verbatim from the installation instructions isn't going to work.  You should pick a date in the future.  Currently, the expiration date is required, but the next update should include an option to create tokens that never expire.

I'll update the instructions to clarify this point.
